package generatedbyassl.as.aes.controller.aeself_management.videoconferencing;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'inProcessingVideo' (specified as FLUENT ASSL tier).
 */
public class INPROCESSINGVIDEO
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INPROCESSINGVIDEO' class.
	 */
	static private INPROCESSINGVIDEO oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INPROCESSINGVIDEO (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.controller.events.VIDEOSTARTED.getInstance() );
		generatedbyassl.as.aes.controller.events.VIDEOSTARTED.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.controller.events.VIDEOPROCESSED.getInstance() );
		generatedbyassl.as.aes.controller.events.VIDEOPROCESSED.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INPROCESSINGVIDEO' class.
	 */
	static public INPROCESSINGVIDEO getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INPROCESSINGVIDEO();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}