package generatedbyassl.as.aes.controller.aeself_management.videoconferencing;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'inStartingingVideo' (specified as FLUENT ASSL tier).
 */
public class INSTARTINGINGVIDEO
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INSTARTINGINGVIDEO' class.
	 */
	static private INSTARTINGINGVIDEO oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INSTARTINGINGVIDEO (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.controller.events.TIMETOSTARTVIDEO.getInstance() );
		generatedbyassl.as.aes.controller.events.TIMETOSTARTVIDEO.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.controller.events.VIDEOSTARTED.getInstance() );
		generatedbyassl.as.aes.controller.events.VIDEOSTARTED.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INSTARTINGINGVIDEO' class.
	 */
	static public INSTARTINGINGVIDEO getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INSTARTINGINGVIDEO();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}