package generatedbyassl.as.aes.controller.aeip.functions;

import java.io.Serializable;
import generatedbyassl.as.ASSLFUNCTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'sendEndSessionMsgs' (specified as FUNCTION ASSL tier).
 */
public class SENDENDSESSIONMSGS
	extends ASSLFUNCTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'SENDENDSESSIONMSGS' class.
	 */
	static private SENDENDSESSIONMSGS oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Action parameter.
	 */
	protected String MEETINGTYPE = null;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  SENDENDSESSIONMSGS (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'SENDENDSESSIONMSGS' class.
	 */
	static public SENDENDSESSIONMSGS getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new SENDENDSESSIONMSGS();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the function.
	 */
	public void DOES (  )
	{
		super.DOES();
		if (  generatedbyassl.as.aes.controller.aeip.functions.SENDENDSESSIONMSGS.getInstance().MEETINGTYPE  ==  "ScheduledMeeting"  ) 
		{
			generatedbyassl.as.aes.controller.aeip.channels.CONTROLLER_LINK.getInstance().putMessage("generatedbyassl.as.aes.controller.aeip.messages.MSGSCHEDULEDMEETINGEND_A", generatedbyassl.as.aes.controller.aeip.messages.MSGSCHEDULEDMEETINGEND_A.getInstance());
			generatedbyassl.as.aes.controller.aeip.channels.CONTROLLER_LINK.getInstance().putMessage("generatedbyassl.as.aes.controller.aeip.messages.MSGSCHEDULEDMEETINGEND_A", generatedbyassl.as.aes.controller.aeip.messages.MSGSCHEDULEDMEETINGEND_A.getInstance());
		}
		else if (  generatedbyassl.as.aes.controller.aeip.functions.SENDENDSESSIONMSGS.getInstance().MEETINGTYPE  ==  "InstantMeeting"  ) 
		{
			generatedbyassl.as.aes.controller.aeip.channels.CONTROLLER_LINK.getInstance().putMessage("generatedbyassl.as.aes.controller.aeip.messages.MSGINSTANTMEETINGEND_A", generatedbyassl.as.aes.controller.aeip.messages.MSGINSTANTMEETINGEND_A.getInstance());
			generatedbyassl.as.aes.controller.aeip.channels.CONTROLLER_LINK.getInstance().putMessage("generatedbyassl.as.aes.controller.aeip.messages.MSGINSTANTMEETINGEND_B", generatedbyassl.as.aes.controller.aeip.messages.MSGINSTANTMEETINGEND_B.getInstance());
		}
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the function (performs with default arguments).
	 */
	public synchronized void perform (  )
	{
		//**** Calls perform() with arguments by default.
		//**** If needed, change the arguments by default with appropriate ones.
		//****************************************************
		perform("");
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the function.
	 */
	public synchronized void perform ( String MEETINGTYPE )
	{
		this.MEETINGTYPE = MEETINGTYPE;
		super.perform();
	}

}