package generatedbyassl.as.aes.user_b.controlloop;

import generatedbyassl.as.controlloop.ASSLEXECUTOR;

/**
 * Generated by ASSL Framework
 * 
 * This is the executor class of the user_b's control loop. An instance of this class participates in the monitor-analyzer-simulator-executor control loop of user_b.
 */
public class USER_B_ASSLEXECUTOR
	extends ASSLEXECUTOR
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * The superclass ASSLEXECUTOR makes this class fully functional. Put your modifications here (if any).
	 */

}