package generatedbyassl.as.asip.functions;

import java.io.Serializable;
import generatedbyassl.as.ASSLFUNCTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'receiveVideoConferenceMsg' (specified as FUNCTION ASSL tier).
 */
public class RECEIVEVIDEOCONFERENCEMSG
	extends ASSLFUNCTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'RECEIVEVIDEOCONFERENCEMSG' class.
	 */
	static private RECEIVEVIDEOCONFERENCEMSG oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Action parameter.
	 */
	protected String USERNAME = null;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  RECEIVEVIDEOCONFERENCEMSG (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'RECEIVEVIDEOCONFERENCEMSG' class.
	 */
	static public RECEIVEVIDEOCONFERENCEMSG getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new RECEIVEVIDEOCONFERENCEMSG();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the function.
	 */
	public void DOES (  )
	{
		super.DOES();
		if (  generatedbyassl.as.asip.functions.RECEIVEVIDEOCONFERENCEMSG.getInstance().USERNAME  ==  "User_A"  ) 
		{
			generatedbyassl.as.asip.channels.VIDEOCONFERENCELINK.getInstance().getMessage("generatedbyassl.as.asip.messages.MSGVIDEOCONFERENCEUSER_A");
		}
		else if (  generatedbyassl.as.asip.functions.RECEIVEVIDEOCONFERENCEMSG.getInstance().USERNAME  ==  "User_B"  ) 
		{
			generatedbyassl.as.asip.channels.VIDEOCONFERENCELINK.getInstance().getMessage("generatedbyassl.as.asip.messages.MSGVIDEOCONFERENCEUSER_B");
		}
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the function (performs with default arguments).
	 */
	public synchronized void perform (  )
	{
		//**** Calls perform() with arguments by default.
		//**** If needed, change the arguments by default with appropriate ones.
		//****************************************************
		perform("");
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the function.
	 */
	public synchronized void perform ( String USERNAME )
	{
		this.USERNAME = USERNAME;
		super.perform();
	}

}