package generatedbyassl.as.autonomicnetwork.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;
import java.lang.Boolean;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'AuthenticateUser' (specified as ACTION ASSL tier).
 */
public class AUTHENTICATEUSER
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'AUTHENTICATEUSER' class.
	 */
	static private AUTHENTICATEUSER oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  AUTHENTICATEUSER (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'AUTHENTICATEUSER' class.
	 */
	static public AUTHENTICATEUSER getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new AUTHENTICATEUSER();
		}
		return oInstance;
	}

}