package generatedbyassl.as.autonomicnetwork.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'processRequest' (specified as ACTION ASSL tier).
 */
public class PROCESSREQUEST
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'PROCESSREQUEST' class.
	 */
	static private PROCESSREQUEST oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Action parameter.
	 */
	protected String USERNAME = null;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  PROCESSREQUEST (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'PROCESSREQUEST' class.
	 */
	static public PROCESSREQUEST getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new PROCESSREQUEST();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.autonomicnetwork.asself_management.self_configuring.INREQUESTVIDEOCONFERENCE_A.getInstance().isFluentInitiated()   ||  generatedbyassl.as.autonomicnetwork.asself_management.self_configuring.INREQUESTVIDEOCONFERENCE_B.getInstance().isFluentInitiated()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.autonomicnetwork.actions.AUTHENTICATEUSER.getInstance().perform(  );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is successfully performed.
	 */
	public void TRIGGERS (  )
	{
		if (  generatedbyassl.as.autonomicnetwork.actions.PROCESSREQUEST.getInstance().USERNAME  ==  "User_A"  ) 
		{
			generatedbyassl.as.autonomicnetwork.events.REQUEST_APROCESSED.getInstance().triggerEvent();
		}
		else if (  generatedbyassl.as.autonomicnetwork.actions.PROCESSREQUEST.getInstance().USERNAME  ==  "User_B"  ) 
		{
			generatedbyassl.as.autonomicnetwork.events.REQUEST_BPROCESSED.getInstance().triggerEvent();
		}
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the action (performs with default arguments).
	 */
	public synchronized void perform (  )
	{
		//**** Calls perform() with arguments by default.
		//**** If needed, change the arguments by default with appropriate ones.
		//****************************************************
		perform("");
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the action.
	 */
	public synchronized void perform ( String USERNAME )
	{
		this.USERNAME = USERNAME;
		super.perform();
	}

}