package generatedbyassl.as.aes.user_a.aeself_management.self_configuring;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'inRequest_A' (specified as FLUENT ASSL tier).
 */
public class INREQUEST_A
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INREQUEST_A' class.
	 */
	static private INREQUEST_A oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INREQUEST_A (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.user_a.events.TIMETOSENDREQUESTA.getInstance() );
		generatedbyassl.as.aes.user_a.events.TIMETOSENDREQUESTA.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.user_a.events.REQUEST_ASENT.getInstance() );
		generatedbyassl.as.aes.user_a.events.REQUEST_ASENT.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INREQUEST_A' class.
	 */
	static public INREQUEST_A getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INREQUEST_A();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}