package generatedbyassl.as.aes.controller;

import java.io.Serializable;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'FRIENDS' (specified as FRIENDS ASSL tier).
 */
public class FRIENDS
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'FRIENDS' class.
	 */
	static private FRIENDS oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  FRIENDS (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'FRIENDS' class.
	 */
	static public FRIENDS getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new FRIENDS();
		}
		return oInstance;
	}

}