package generatedbyassl.as.aes.controller.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'processMeetingType' (specified as ACTION ASSL tier).
 */
public class PROCESSMEETINGTYPE
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'PROCESSMEETINGTYPE' class.
	 */
	static private PROCESSMEETINGTYPE oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Action parameter.
	 */
	protected String MEETINGTYPE = null;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  PROCESSMEETINGTYPE (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'PROCESSMEETINGTYPE' class.
	 */
	static public PROCESSMEETINGTYPE getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new PROCESSMEETINGTYPE();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		super.DOES();
		if (  generatedbyassl.as.aes.CONTROLLER.getInstance().INITIATEWITHA  ) 
		{
			if (  generatedbyassl.as.aes.controller.actions.PROCESSMEETINGTYPE.getInstance().MEETINGTYPE  ==  "ScheduledMeeting"  ) 
			{
				generatedbyassl.as.aes.controller.aeip.managed_elements.MEETINGTOOL_A.getInstance().SCHEDULEDMEETINGINTERFACE(  );
			}
			if (  generatedbyassl.as.aes.controller.actions.PROCESSMEETINGTYPE.getInstance().MEETINGTYPE  ==  "InstantMeeting"  ) 
			{
				generatedbyassl.as.aes.controller.aeip.managed_elements.MEETINGTOOL_A.getInstance().INSTANTMEETINGINTERFACE(  );
			}
		}
		else if (  generatedbyassl.as.aes.controller.actions.PROCESSMEETINGTYPE.getInstance().MEETINGTYPE  ==  "ScheduledMeeting"  ) 
		{
			generatedbyassl.as.aes.controller.aeip.managed_elements.MEETINGTOOL_B.getInstance().SCHEDULEDMEETINGINTERFACE(  );
		}
		else if (  generatedbyassl.as.aes.controller.actions.PROCESSMEETINGTYPE.getInstance().MEETINGTYPE  ==  "InstantMeeting"  ) 
		{
			generatedbyassl.as.aes.controller.aeip.managed_elements.MEETINGTOOL_B.getInstance().INSTANTMEETINGINTERFACE(  );
		}
		generatedbyassl.as.aes.controller.aeip.functions.SENDBEGINMSGS.getInstance().perform( generatedbyassl.as.aes.controller.actions.PROCESSMEETINGTYPE.getInstance().MEETINGTYPE );
		generatedbyassl.as.aes.controller.aeip.functions.SENDVIDEOCONFERENCEMSG.getInstance().perform(  );
		generatedbyassl.as.aes.controller.aeip.functions.SENDENDSESSIONMSGS.getInstance().perform( generatedbyassl.as.aes.controller.actions.PROCESSMEETINGTYPE.getInstance().MEETINGTYPE );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the action (performs with default arguments).
	 */
	public synchronized void perform (  )
	{
		//**** Calls perform() with arguments by default.
		//**** If needed, change the arguments by default with appropriate ones.
		//****************************************************
		perform("");
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the action.
	 */
	public synchronized void perform ( String MEETINGTYPE )
	{
		this.MEETINGTYPE = MEETINGTYPE;
		super.perform();
	}

}