package generatedbyassl.as.aes.controller.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;
import java.lang.Boolean;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'StartVideo' (specified as ACTION ASSL tier).
 */
public class STARTVIDEO
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'STARTVIDEO' class.
	 */
	static private STARTVIDEO oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  STARTVIDEO (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'STARTVIDEO' class.
	 */
	static public STARTVIDEO getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new STARTVIDEO();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.aes.controller.aeself_management.videoconferencing.INSTARTINGINGVIDEO.getInstance().isFluentInitiated()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		super.DOES();
		if (  generatedbyassl.as.aes.CONTROLLER.getInstance().INITIATEWITHA  ) 
		{
			generatedbyassl.as.aes.controller.aeip.managed_elements.MEETINGTOOL_A.getInstance().STARTVIDEO(  );
			generatedbyassl.as.aes.CONTROLLER.getInstance().INITIATEWITHA = false ;
		}
		else
		{
			generatedbyassl.as.aes.controller.aeip.managed_elements.MEETINGTOOL_B.getInstance().STARTVIDEO(  );
			generatedbyassl.as.aes.CONTROLLER.getInstance().INITIATEWITHA = true ;
		}
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is successfully performed.
	 */
	public void TRIGGERS (  )
	{
		generatedbyassl.as.aes.controller.events.VIDEOSTARTED.getInstance().triggerEvent();
	}

}