package generatedbyassl.as.aes.user_b.aeself_management;

import java.io.Serializable;
import generatedbyassl.as.ASSLPOLICY;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'VideoConferencing' (specified as POLICY ASSL tier).
 */
public class VIDEOCONFERENCING
	extends ASSLPOLICY
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'VIDEOCONFERENCING' class.
	 */
	static private VIDEOCONFERENCING oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  VIDEOCONFERENCING (  )
	{
		vFluents.put( "INSTARTINGSCHEDULEDMEETINGSESSION", generatedbyassl.as.aes.user_b.aeself_management.videoconferencing.INSTARTINGSCHEDULEDMEETINGSESSION.getInstance() );
		vFluents.put( "INSTARTINGINSTANTMEETINGSESSION", generatedbyassl.as.aes.user_b.aeself_management.videoconferencing.INSTARTINGINSTANTMEETINGSESSION.getInstance() );
		vFluents.put( "INRECORDINGSCHEDULEDMEETING", generatedbyassl.as.aes.user_b.aeself_management.videoconferencing.INRECORDINGSCHEDULEDMEETING.getInstance() );
		vFluents.put( "INRECORDINGINSTANTMEETING", generatedbyassl.as.aes.user_b.aeself_management.videoconferencing.INRECORDINGINSTANTMEETING.getInstance() );
		vFluents.put( "INSENDINGVIDEO", generatedbyassl.as.aes.user_b.aeself_management.videoconferencing.INSENDINGVIDEO.getInstance() );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'VIDEOCONFERENCING' class.
	 */
	static public VIDEOCONFERENCING getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new VIDEOCONFERENCING();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * For each specified MAPPING, checks if the MAPPING conditions are fulfilled and if so spawn a thread to perform the MAPPING actions.
	 */
	public synchronized void doAllMappings (  )
	{
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.user_b.aeself_management.videoconferencing.INSTARTINGSCHEDULEDMEETINGSESSION.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.user_b.actions.STARTVIDEORECORDINGSESSION.getInstance().perform( "ScheduledMeeting" );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INSTARTINGSCHEDULEDMEETINGSESSION" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INSTARTINGSCHEDULEDMEETINGSESSION");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.user_b.aeself_management.videoconferencing.INSTARTINGINSTANTMEETINGSESSION.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.user_b.actions.STARTVIDEORECORDINGSESSION.getInstance().perform( "InstantMeeting" );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INSTARTINGINSTANTMEETINGSESSION" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INSTARTINGINSTANTMEETINGSESSION");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.user_b.aeself_management.videoconferencing.INRECORDINGSCHEDULEDMEETING.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.user_b.actions.RECORDMEETING.getInstance().perform( "ScheduledMeeting" );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INRECORDINGSCHEDULEDMEETING" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INRECORDINGSCHEDULEDMEETING");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.user_b.aeself_management.videoconferencing.INRECORDINGINSTANTMEETING.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.user_b.actions.RECORDMEETING.getInstance().perform( "InstantMeeting" );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INRECORDINGINSTANTMEETING" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INRECORDINGINSTANTMEETING");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.user_b.aeself_management.videoconferencing.INSENDINGVIDEO.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.user_b.actions.SENDVIDEO.getInstance().perform(  );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INSENDINGVIDEO" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INSENDINGVIDEO");
				runActions.start();
			}
		}
	}

}