package generatedbyassl.as.aes.user_b.aeself_management.self_configuring;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'inRequest_B' (specified as FLUENT ASSL tier).
 */
public class INREQUEST_B
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INREQUEST_B' class.
	 */
	static private INREQUEST_B oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INREQUEST_B (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.user_b.events.TIMETOSENDREQUESTB.getInstance() );
		generatedbyassl.as.aes.user_b.events.TIMETOSENDREQUESTB.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.user_b.events.REQUEST_BSENT.getInstance() );
		generatedbyassl.as.aes.user_b.events.REQUEST_BSENT.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INREQUEST_B' class.
	 */
	static public INREQUEST_B getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INREQUEST_B();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}