package generatedbyassl.as.aes;

import java.io.Serializable;
import generatedbyassl.as.ASSLAE;
import generatedbyassl.as.aes.user_b.controlloop.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'User_B' (specified as AE ASSL tier).
 */
public class USER_B
	extends ASSLAE
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'USER_B' class.
	 */
	static private USER_B oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's monitor.
	 */
	private USER_B_ASSLMONITOR oMonitor = new USER_B_ASSLMONITOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's analyzer.
	 */
	private USER_B_ASSLANALYZER oAnalyzer = new USER_B_ASSLANALYZER();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's simulator.
	 */
	private USER_B_ASSLSIMULATOR oSimulator = new USER_B_ASSLSIMULATOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's executor.
	 */
	private USER_B_ASSLEXECUTOR oExecutor = new USER_B_ASSLEXECUTOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AEIP class.
	 */
	public generatedbyassl.as.aes.user_b.AEIP AEIP = generatedbyassl.as.aes.user_b.AEIP.getInstance();

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  USER_B (  )
	{
		vPolicies.put( "SELF_CONFIGURING", generatedbyassl.as.aes.user_b.aeself_management.SELF_CONFIGURING.getInstance() );
		vPolicies.put( "VIDEOCONFERENCING", generatedbyassl.as.aes.user_b.aeself_management.VIDEOCONFERENCING.getInstance() );
		ACTIONS.put( "REQUEST", generatedbyassl.as.aes.user_b.actions.REQUEST.getInstance() );
		ACTIONS.put( "STARTVIDEORECORDINGSESSION", generatedbyassl.as.aes.user_b.actions.STARTVIDEORECORDINGSESSION.getInstance() );
		ACTIONS.put( "RECORDMEETING", generatedbyassl.as.aes.user_b.actions.RECORDMEETING.getInstance() );
		ACTIONS.put( "VIDEOPREPRATION", generatedbyassl.as.aes.user_b.actions.VIDEOPREPRATION.getInstance() );
		ACTIONS.put( "SENDVIDEO", generatedbyassl.as.aes.user_b.actions.SENDVIDEO.getInstance() );
		EVENTS.put( "TIMETOSENDREQUESTB", generatedbyassl.as.aes.user_b.events.TIMETOSENDREQUESTB.getInstance() );
		EVENTS.put( "REQUEST_BSENT", generatedbyassl.as.aes.user_b.events.REQUEST_BSENT.getInstance() );
		EVENTS.put( "SCHEDULEDMEETINGSESSIONISSTARTING", generatedbyassl.as.aes.user_b.events.SCHEDULEDMEETINGSESSIONISSTARTING.getInstance() );
		EVENTS.put( "INSTANTMEETINGSESSIONISSTARTING", generatedbyassl.as.aes.user_b.events.INSTANTMEETINGSESSIONISSTARTING.getInstance() );
		EVENTS.put( "SCHEDULEDMEETINGSESSIONSTARTED", generatedbyassl.as.aes.user_b.events.SCHEDULEDMEETINGSESSIONSTARTED.getInstance() );
		EVENTS.put( "MEETINGSESSIONENDEDSCHEDULEDMEETING", generatedbyassl.as.aes.user_b.events.MEETINGSESSIONENDEDSCHEDULEDMEETING.getInstance() );
		EVENTS.put( "INSTANTMEETINGSESSIONSTARTED", generatedbyassl.as.aes.user_b.events.INSTANTMEETINGSESSIONSTARTED.getInstance() );
		EVENTS.put( "MEETINGSESSIONENDEDINSTANTMEETING", generatedbyassl.as.aes.user_b.events.MEETINGSESSIONENDEDINSTANTMEETING.getInstance() );
		EVENTS.put( "VIDEOUSER_BSENT", generatedbyassl.as.aes.user_b.events.VIDEOUSER_BSENT.getInstance() );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'USER_B' class.
	 */
	static public USER_B getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new USER_B();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Sets the control loop components.
	 */
	protected void setControlLoop (  )
	{
		//**** This method overrides the super class's method.
		//****************************************************
		oMonitor.setMonitoredSLO(AESLO);
		oMonitor.setMonitoredMetrics(METRICS);
		oMonitor.setAnalyzer(oAnalyzer);
		oAnalyzer.setSimulator(oSimulator);
		oAnalyzer.setExecutor(oExecutor);
		oSimulator.setExecutor(oExecutor);
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the AE control loop.
	 */
	protected void controlLoop (  )
	{
		//**** This method overrides the super class's method.
		//****************************************************
		try
		{
			//**** control loops should not be very resource-consuming, thus it releases CPU for a while
			Thread.sleep(1000);
		}
		catch ( InterruptedException ex ) 
		{
			System.err.println( ex.getMessage() );
		}
		//**** performs AE control loop monitor-analyzer-simulator-executor
		oMonitor.perform();
		oAnalyzer.perform();
		oSimulator.perform();
		oExecutor.perform();
		//**** applies all the "switched-on" self-management policies for the AS
		applayPolicies();
	}

}