package generatedbyassl.as.aes.user_a.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'SendVideo' (specified as ACTION ASSL tier).
 */
public class SENDVIDEO
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'SENDVIDEO' class.
	 */
	static private SENDVIDEO oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  SENDVIDEO (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'SENDVIDEO' class.
	 */
	static public SENDVIDEO getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new SENDVIDEO();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.aes.user_a.aeself_management.videoconferencing.INSENDINGVIDEO.getInstance().isFluentInitiated()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.aes.user_a.actions.VIDEOPREPRATION.getInstance().perform(  );
		generatedbyassl.as.asip.functions.SENDVIDEOCONFERENCEMSG.getInstance().perform( "User_A" );
		generatedbyassl.as.asip.functions.RECEIVEVIDEOCONFERENCEMSG.getInstance().perform( "User_A" );
	}

}