package generatedbyassl.as.aes.user_a.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'startVideoRecordingSession' (specified as ACTION ASSL tier).
 */
public class STARTVIDEORECORDINGSESSION
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'STARTVIDEORECORDINGSESSION' class.
	 */
	static private STARTVIDEORECORDINGSESSION oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Action parameter.
	 */
	protected String MEETINGTYPE = null;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  STARTVIDEORECORDINGSESSION (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'STARTVIDEORECORDINGSESSION' class.
	 */
	static public STARTVIDEORECORDINGSESSION getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new STARTVIDEORECORDINGSESSION();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.aes.user_a.aeself_management.videoconferencing.INSTARTINGSCHEDULEDMEETINGSESSION.getInstance().isFluentInitiated()   ||  generatedbyassl.as.aes.user_a.aeself_management.videoconferencing.INSTARTINGINSTANTMEETINGSESSION.getInstance().isFluentInitiated()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.aes.user_a.aeip.functions.RECEIVEBEGINMSG.getInstance().perform( generatedbyassl.as.aes.user_a.actions.STARTVIDEORECORDINGSESSION.getInstance().MEETINGTYPE );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the action (performs with default arguments).
	 */
	public synchronized void perform (  )
	{
		//**** Calls perform() with arguments by default.
		//**** If needed, change the arguments by default with appropriate ones.
		//****************************************************
		perform("");
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the action.
	 */
	public synchronized void perform ( String MEETINGTYPE )
	{
		this.MEETINGTYPE = MEETINGTYPE;
		super.perform();
	}

}