package generatedbyassl.as.aes.user_a.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'VideoPrepration' (specified as ACTION ASSL tier).
 */
public class VIDEOPREPRATION
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'VIDEOPREPRATION' class.
	 */
	static private VIDEOPREPRATION oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  VIDEOPREPRATION (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'VIDEOPREPRATION' class.
	 */
	static public VIDEOPREPRATION getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new VIDEOPREPRATION();
		}
		return oInstance;
	}

}