package generatedbyassl.as.asip.channels;

import java.io.Serializable;
import generatedbyassl.as.ASSLCHANNEL;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'VideoConferenceLink' (specified as CHANNEL ASSL tier).
 */
public class VIDEOCONFERENCELINK
	extends ASSLCHANNEL
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'VIDEOCONFERENCELINK' class.
	 */
	static private VIDEOCONFERENCELINK oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  VIDEOCONFERENCELINK (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'VIDEOCONFERENCELINK' class.
	 */
	static public VIDEOCONFERENCELINK getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new VIDEOCONFERENCELINK();
		}
		return oInstance;
	}

}