package generatedbyassl.as.aes.controller.aeip.messages;

import java.io.Serializable;
import generatedbyassl.as.ASSLMESSAGE;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'msgInstantMeetingBegin_A' (specified as MESSAGE ASSL tier).
 */
public class MSGINSTANTMEETINGBEGIN_A
	extends ASSLMESSAGE
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'MSGINSTANTMEETINGBEGIN_A' class.
	 */
	static private MSGINSTANTMEETINGBEGIN_A oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  MSGINSTANTMEETINGBEGIN_A (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'MSGINSTANTMEETINGBEGIN_A' class.
	 */
	static public MSGINSTANTMEETINGBEGIN_A getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new MSGINSTANTMEETINGBEGIN_A();
		}
		return oInstance;
	}

}