package generatedbyassl.as.autonomicnetwork.controlloop;

import generatedbyassl.as.controlloop.ASSLEXECUTOR;

/**
 * Generated by ASSL Framework
 * 
 * This is the executor class of the autonomicnetwork's control loop. An instance of this class participates in the monitor-analyzer-simulator-executor control loop of autonomicnetwork.
 */
public class AUTONOMICNETWORK_ASSLEXECUTOR
	extends ASSLEXECUTOR
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * The superclass ASSLEXECUTOR makes this class fully functional. Put your modifications here (if any).
	 */

}