package generatedbyassl.as.autonomicnetwork.controlloop;

import generatedbyassl.as.controlloop.ASSLMONITOR;

/**
 * Generated by ASSL Framework
 * 
 * This is the monitor class of the autonomicnetwork's control loop. An instance of this class participates in the monitor-analyzer-simulator-executor control loop of autonomicnetwork.
 */
public class AUTONOMICNETWORK_ASSLMONITOR
	extends ASSLMONITOR
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * The superclass ASSLMONITOR makes this class fully functional. Put your modifications here (if any).
	 */

}