package generatedbyassl.as.aes.controller.aeip.managed_elements;

import java.io.Serializable;
import generatedbyassl.as.ASSLMANAGED_ELEMENT;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'MeetingTool_A' (specified as MANAGED_ELEMENT ASSL tier).
 */
public class MEETINGTOOL_A
	extends ASSLMANAGED_ELEMENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'MEETINGTOOL_A' class.
	 */
	static private MEETINGTOOL_A oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  MEETINGTOOL_A (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'MEETINGTOOL_A' class.
	 */
	static public MEETINGTOOL_A getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new MEETINGTOOL_A();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Management element interface function.
	 */
	public void STARTVIDEO (  )
	{
		//**** Implement this method.
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Management element interface function.
	 */
	public void SCHEDULEDMEETINGINTERFACE (  )
	{
		//**** Implement this method.
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Management element interface function.
	 */
	public void INSTANTMEETINGINTERFACE (  )
	{
		//**** Implement this method.
	}

}