package generatedbyassl.as.autonomicnetwork.asself_management;

import java.io.Serializable;
import generatedbyassl.as.ASSLPOLICY;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'VideoConferencing' (specified as POLICY ASSL tier).
 */
public class VIDEOCONFERENCING
	extends ASSLPOLICY
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'VIDEOCONFERENCING' class.
	 */
	static private VIDEOCONFERENCING oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  VIDEOCONFERENCING (  )
	{
		vFluents.put( "INPROCESSINGVIDEOCONFERENCE_A", generatedbyassl.as.autonomicnetwork.asself_management.videoconferencing.INPROCESSINGVIDEOCONFERENCE_A.getInstance() );
		vFluents.put( "INPROCESSINGVIDEOCONFERENCE_B", generatedbyassl.as.autonomicnetwork.asself_management.videoconferencing.INPROCESSINGVIDEOCONFERENCE_B.getInstance() );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'VIDEOCONFERENCING' class.
	 */
	static public VIDEOCONFERENCING getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new VIDEOCONFERENCING();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * For each specified MAPPING, checks if the MAPPING conditions are fulfilled and if so spawn a thread to perform the MAPPING actions.
	 */
	public synchronized void doAllMappings (  )
	{
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.autonomicnetwork.asself_management.videoconferencing.INPROCESSINGVIDEOCONFERENCE_A.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.autonomicnetwork.actions.PROCESSVIDEOCONFERENCE.getInstance().perform( "User_A" );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INPROCESSINGVIDEOCONFERENCE_A" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INPROCESSINGVIDEOCONFERENCE_A");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.autonomicnetwork.asself_management.videoconferencing.INPROCESSINGVIDEOCONFERENCE_B.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.autonomicnetwork.actions.PROCESSVIDEOCONFERENCE.getInstance().perform( "User_B" );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INPROCESSINGVIDEOCONFERENCE_B" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INPROCESSINGVIDEOCONFERENCE_B");
				runActions.start();
			}
		}
	}

}