package generatedbyassl.as.aes.user_a.aeself_management.videoconferencing;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'inStartingInstantMeetingSession' (specified as FLUENT ASSL tier).
 */
public class INSTARTINGINSTANTMEETINGSESSION
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INSTARTINGINSTANTMEETINGSESSION' class.
	 */
	static private INSTARTINGINSTANTMEETINGSESSION oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INSTARTINGINSTANTMEETINGSESSION (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.user_a.events.INSTANTMEETINGSESSIONISSTARTING.getInstance() );
		generatedbyassl.as.aes.user_a.events.INSTANTMEETINGSESSIONISSTARTING.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.user_a.events.INSTANTMEETINGSESSIONSTARTED.getInstance() );
		generatedbyassl.as.aes.user_a.events.INSTANTMEETINGSESSIONSTARTED.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INSTARTINGINSTANTMEETINGSESSION' class.
	 */
	static public INSTARTINGINSTANTMEETINGSESSION getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INSTARTINGINSTANTMEETINGSESSION();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}