package generatedbyassl.as;

/**
 * Generated by ASSL Framework
 * 
 * This interface is implemented by all the ASSL event-catcher classes, i.e. fluents, actions etc.
 */
public interface ASSLEVENTCATCHER
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method notifies the ASSL event-catcher class that a specific event has been prompted.
	 */
	public void notifyForEvent ( ASSLEVENT poEvent );
}