package generatedbyassl.as;

/**
 * Generated by ASSL Framework
 * 
 * This is the superclass for all ASSL AS/AE actions.
 */
public class ASSLACTION
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds the message to be printed before performing the action.
	 */
	protected String sMessage = "";

	/**
	 * Generated by ASSL Framework
	 * 
	 * Sets the message to be printed before performing the action.
	 */
	public void setActionMsg ( String psMsg )
	{
		sMessage = psMsg;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		return true;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be ensured at the end of the action execution.
	 */
	public boolean ENSURES (  )
	{
		return true;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Returns the action result if any. If no RETURNS clause has been specified the method returns an instance of Java Object class.
	 */
	public Object RETURNS (  )
	{
		return new Object();
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is successfully performed.
	 */
	public void TRIGGERS (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Triggers events in case the action is not successfully performed.
	 */
	public void ONERR_TRIGGERS (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		if ( !sMessage.isEmpty() ) 
		{
			System.out.println( sMessage );
		}
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are not fulfilled or an exception has occurred during the action performance.
	 */
	public void ONERR_DOES (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the action.
	 */
	public synchronized void perform (  )
	{
		//**** Do not change this method. This implementation follows the Operational Semantics for ASSL Actions.
		if ( GUARDS() ) 
		{
			try
			{
				DOES();
				if ( ENSURES() ) 
				{
					String sMsg = "ACTION '" + this.getClass().getName() + "': has been performed";
					System.out.println( sMsg );
					TRIGGERS();
				}
				else
				{
					String sMsg = "ACTION '" + this.getClass().getName() + "': has failed to fulfill ENSURES post-conditions";
					System.out.println( sMsg );
					ONERR_DOES();
					ONERR_TRIGGERS();
				}
			}
			catch ( Exception ex ) 
			{
				ONERR_DOES();
				ONERR_TRIGGERS();
			}
		}
		else
		{
			String sMsg = "ACTION '" + this.getClass().getName() + "':  has been prevented by GUARDS";
			System.out.println( sMsg );
			ONERR_DOES();
			ONERR_TRIGGERS();
		}
	}

}