package generatedbyassl.as;

/**
 * Generated by ASSL Framework
 * 
 * This interface is implemented by all the ASSL message-catcher classes, e.g., events prompted when a message has been sent or received.
 */
public interface ASSLMESSAGECATCHER
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * Notifies the ASSL message-catcher class that a specific message has been received.
	 */
	public void notifyForReceivedMessage ( ASSLMESSAGE poMessage );
	/**
	 * Generated by ASSL Framework
	 * 
	 * Notifies the ASSL message-catcher class that a specific message has been sent.
	 */
	public void notifyForSentMessage ( ASSLMESSAGE poMessage );
}