package generatedbyassl.as;

/**
 * Generated by ASSL Framework
 * 
 * This is the superclass for all ASSL functions.
 */
public class ASSLFUNCTION
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds the message to be printed before performing the function.
	 */
	protected String sMessage = "";

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the function.
	 */
	public void DOES (  )
	{
		if ( !sMessage.isEmpty() ) 
		{
			System.out.println( sMessage );
		}
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Sets the message to be printed before performing the function.
	 */
	public void setFunctionMsg ( String psMsg )
	{
		sMessage = psMsg;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the function.
	 */
	public synchronized void perform (  )
	{
		//**** Override this method in descendant classes.
		DOES();
	}

}