package generatedbyassl.as;

/**
 * Generated by ASSL Framework
 * 
 * This is the superclass for all ASSL AS/AE SLO.
 */
public class ASSLSLO
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * Checks whether the SLO are satisfied.
	 */
	public synchronized boolean isSatisfied (  )
	{
		// Override this method in descendant classes. 
		return true;
	}

}