package generatedbyassl.as;

import java.util.Hashtable;

/**
 * Generated by ASSL Framework
 * 
 * This is the superclass for all ASSL ASARCHITECTURE groups.
 */
public class ASSLGROUP
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds the group's name.
	 */
	protected String sName = "";
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds pairs 'AE name'-'AE reference' of all the autonomic elements specified by the MEMBERS clause in the group.
	 */
	protected Hashtable<String, ASSLAE> MEMBERS = new Hashtable<String, ASSLAE>();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds pairs 'AE name'-'AE reference' of all the autonomic elements specified by the COUNCIL clause in the group.
	 */
	protected Hashtable<String, ASSLAE> COUNCIL = new Hashtable<String, ASSLAE>();

	/**
	 * Generated by ASSL Framework
	 * 
	 * Returns a reference to a group member specified by name.
	 */
	public ASSLAE getMember ( String psAEName )
	{
		return MEMBERS.get(psAEName);
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Adds an AE to MEMBERS.
	 */
	public void addToMembers ( String psAEName, ASSLAE poAE )
	{
		MEMBERS.put(psAEName, poAE);
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Returns a reference to a group council member specified by name.
	 */
	public ASSLAE getCouncilMember ( String psAEName )
	{
		return COUNCIL.get(psAEName);
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Adds an AE to COUNCIL.
	 */
	public void addToCouncil ( String psAEName, ASSLAE poAE )
	{
		COUNCIL.put(psAEName, poAE);
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Creates an instance of class ASSLGROUP.
	 */
	public  ASSLGROUP ( String psName )
	{
		sName = psName;
	}

}