package generatedbyassl.as;

import java.util.Hashtable;

/**
 * Generated by ASSL Framework
 * 
 * This is the superclass for all ASSL ASARCHITECTURE DEPENDENCY tiers (DIRECT_DEPENDENCIES and TRANSITIVE_DEPENDENCIES).
 */
public class ASSLDEPENDENCY
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds the dependency's name.
	 */
	protected String sName = "";
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds pairs 'AE name'-'AE reference' of all the autonomic elements specified by the dependecy.
	 */
	protected Hashtable<String, ASSLAE> AES = new Hashtable<String, ASSLAE>();

	/**
	 * Generated by ASSL Framework
	 * 
	 * Returns a reference to a dependency member specified by name.
	 */
	public ASSLAE getDependencyMember ( String psAEName )
	{
		return AES.get(psAEName);
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Adds an AE to this dependency..
	 */
	public void addToDependency ( String psAEName, ASSLAE poAE )
	{
		AES.put(psAEName, poAE);
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Creates an instance of class ASSLDEPENDENCY.
	 */
	public  ASSLDEPENDENCY ( String psName )
	{
		sName = psName;
	}

}