package generatedbyassl.as;

/**
 * Generated by ASSL Framework
 * 
 * This is the superclass for all ASSL AE OUTCOME.
 */
public class ASSLOUTCOME
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * Produces the outcome.
	 */
	public synchronized void produce (  )
	{
		String sMsg = "OUTCOME '" + this.getClass().getName() + "': has been produced";
		System.out.println( sMsg );
		//********************************************************
		//**** This method should be overridden by descendant classes
	}

}