package generatedbyassl.as.autonomicnetwork.asself_management.videoconferencing;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'inProcessingVideoConference_A' (specified as FLUENT ASSL tier).
 */
public class INPROCESSINGVIDEOCONFERENCE_A
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INPROCESSINGVIDEOCONFERENCE_A' class.
	 */
	static private INPROCESSINGVIDEOCONFERENCE_A oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INPROCESSINGVIDEOCONFERENCE_A (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.autonomicnetwork.events.VIDEOCONFERENCE_ARECEIVED.getInstance() );
		generatedbyassl.as.autonomicnetwork.events.VIDEOCONFERENCE_ARECEIVED.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.autonomicnetwork.events.VIDEOCONFERENCE_APROCESSED.getInstance() );
		generatedbyassl.as.autonomicnetwork.events.VIDEOCONFERENCE_APROCESSED.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INPROCESSINGVIDEOCONFERENCE_A' class.
	 */
	static public INPROCESSINGVIDEOCONFERENCE_A getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INPROCESSINGVIDEOCONFERENCE_A();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}